// node train.js [generations] [outfile]  — RL (evolution strategies, self-play) for the brains.
const E = require('./js/env.js'), R = require('./js/roster.js'), P = require('./js/policy.js'), ES = require('./js/es.js');
const fs = require('fs');
const gens = parseInt(process.argv[2] || '300', 10), out = process.argv[3] || 'js/brains.js';
const cfg = Object.assign({}, ES.DEFAULTS, { roster: R.FIGURES, gorilla: R.GORILLA });
if (process.env.ONLY_SIDE) { cfg.onlySide = process.env.ONLY_SIDE; cfg.scriptedOppProb = 0.4; console.log('training only the', cfg.onlySide, 'side'); }
let init = null;
if (fs.existsSync(out)) { try { const prev = require('./' + out); if (prev && prev.human && prev.human.length === P.HUMAN_MLP.nParams) { init = prev; console.log('resuming from', out, 'gen', prev.meta && prev.meta.generations); } } catch (e) {} }
const state = ES.createState(cfg, init);
if (init && init.meta) state.gen = init.meta.generations || 0;
const t0 = Date.now();
function save(tag) {
  const meta = { generations: state.gen, trainedAt: new Date().toISOString(), cfg: { popSize: cfg.popSize, sigma: cfg.sigma, lr: cfg.lr, episodes: cfg.episodes, phaseLen: cfg.phaseLen, nRange: cfg.nRange, timeLimit: cfg.timeLimit }, history: state.history.slice(-400).map(h => ({ g: h.gen, s: h.side[0], f: +h.current.toFixed(3), w: +h.humanWinRate.toFixed(3) })), note: tag };
  const body = `/* brains.js — RL-trained policy weights (evolution strategies, self-play). Generated by train.js. */\n(function (root) {\n  var B = ${JSON.stringify({ human: Array.from(state.human, x => +x.toFixed(5)), gorilla: Array.from(state.gorilla, x => +x.toFixed(5)), meta })};\n  if (typeof module === 'object' && module.exports) module.exports = B; else root.GORILLA_BRAINS = B;\n})(typeof self !== 'undefined' ? self : this);\n`;
  fs.writeFileSync(out, body);
}
ES.trainSteps(state, cfg, gens, (st) => {
  const el = ((Date.now() - t0) / 1000).toFixed(0);
  console.log(`gen ${String(st.gen).padStart(4)} ${st.side.padEnd(7)} mean=${st.mean.toFixed(3)} best=${st.best.toFixed(3)} cur=${st.current.toFixed(3)} humanWin=${(st.humanWinRate * 100).toFixed(0)}% [${el}s]`);
  if (state.gen % 10 === 0) save('checkpoint');
});
save('final');
console.log('saved', out);
